#服务器端口
server:
  port: 8206
#数据源配置
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/blade?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8858
    nacos:
      server-addr: localhost:8848
  application:
    name: producer-demo